language: "en-US"
early_access: false
reviews:
    profile: assertive
    request_changes_workflow: false
    high_level_summary: true
    poem: false
    review_status: false
    collapse_walkthrough: false
    sequence_diagrams: true
    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT MERGE"
        base_branches:
            - "master"
            - "development"
            - "release/*"
chat:
    auto_reply: true
    