options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_ENV: "test"  #  the target environment (test, release, etc.)
  _FIREBASE_PROJECT_ID: "your-project-id"  # Replacing with your dynamic project ID
  _FIREBASE_SITE_ID: "${_BUILD_ENV}_site_id"  # Placeholder for Firebase site ID

steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Conditionally run builds based on _BUILD_ENV
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build env:" ${_BUILD_ENV}
        case "${_BUILD_ENV}" in
          "test") npm run build-test ;;
          "release") npm run build-release ;;
          "staging") npm run build-staging ;;
          "prod") npm run build-prod ;;
          "prod-enterprise") npm run build-prod-enterprise ;;
          "prod-in") npm run build-prod-in ;;
          "prod-eu") npm run build-prod-eu ;;
          "prod-cn") npm run build-prod-cn ;;
          "prod_beta") npm run build-beta ;;
          *) npm run build-test ;;
        esac

  # Step 3: Updated firebase.json dynamically
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Updating firebase.json with site ID..."
        sed -i 's/"site": ".*"/"site": "'"${_FIREBASE_SITE_ID}"'"/' firebase.json

  # Step 4: Validating the build directory contains index.html
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Checking if webplugin/build contains index.html..."
        if [ ! -f "webplugin/build/index.html" ]; then
          echo "Error: index.html not found in webplugin/build. Build process might have failed."
          exit 1
        fi
        echo "firebase.json exists, now validating its structure..."
        if [ ! -f "firebase.json" ]; then
          echo "Error: firebase.json file does not exist."
          exit 1
        fi

  # Step 5: Deploy to Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - 'deploy'
      - '--only'
      - 'hosting:${_FIREBASE_SITE_ID}'
      - '--project'
      - '${_FIREBASE_PROJECT_ID}'
      - '--token'
      - '${_FIREBASE_TOKEN}'
