options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_ENV: "test"  # Can be set per environment (test, release)
  _FIREBASE_PROJECT_ID: "your-project-id"  # Will be set dynamically in the build trigger
  _FIREBASE_SITE_ID: "${_BUILD_ENV}_site_id"  # Firebase site ID for the environment

steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Conditionally run builds based on _BUILD_ENV
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build env:" ${_BUILD_ENV}
        if [ "${_BUILD_ENV}" = "test" ]; then npm run build-test;
        elif [ "${_BUILD_ENV}" = "release" ]; then npm run build-release;
        else npm run build-test;
        fi

  # Step 3: Deploy to Firebase Hosting with dynamic site ID
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - '${_FIREBASE_PROJECT_ID}'
      - '--token'
      - '${_FIREBASE_TOKEN}'
    env:
      - "FIREBASE_SITE_ID=${_FIREBASE_SITE_ID}"  # Dynamic site ID as an environment variable
