options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_ENV: "test"
  _DEPLOY_CDN: "false"
  _CDN_BUCKET: "your-cdn-bucket"
  _FIREBASE_PROJECT_ID: "your-project-id"
  _FIREBASE_SITE_ID: "your-site-id"

steps:
# ------------------------------------------------------------
# Step 1: Install Node.js dependencies
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Cleaning npm cache"
      npm cache clean --force
      rm -rf node_modules package-lock.json
      echo "Installing dependencies"
      npm install

# ------------------------------------------------------------
# Step 2: Build based on environment
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'sh'
  env:
    - '_BUILD_ENV=$_BUILD_ENV'
  args:
    - '-c'
    - |
      echo "Build env: $_BUILD_ENV"
      if [ "$_BUILD_ENV" = "test" ]; then
        npm run build-test
      elif [ "$_BUILD_ENV" = "release" ]; then
        npm run build-release
      elif [ "$_BUILD_ENV" = "staging" ]; then
        npm run build-staging
      elif [ "$_BUILD_ENV" = "prod" ]; then
        npm run build-prod
      elif [ "$_BUILD_ENV" = "prod-enterprise" ]; then
        npm run build-prod-enterprise
      elif [ "$_BUILD_ENV" = "prod-in" ]; then
        npm run build-prod-in
      elif [ "$_BUILD_ENV" = "prod_agenticfirst" ]; then
        npm run build-prod-agenticfirst
      elif [ "$_BUILD_ENV" = "prod-eu" ]; then
        npm run build-prod-eu
      elif [ "$_BUILD_ENV" = "prod_cn" ]; then
        npm run build-prod-cn
      elif [ "$_BUILD_ENV" = "prod_beta" ]; then
        npm run build-beta
      else
        npm run build-test
      fi

# ------------------------------------------------------------
# Step 3: Update firebase.json dynamically
# ------------------------------------------------------------
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Updating firebase.json site ID"
      sed -i 's/"site": ".*"/"site": "'"$_FIREBASE_SITE_ID"'"/' firebase.json

# ------------------------------------------------------------
# Step 4: Validate build output
# ------------------------------------------------------------
- name: 'alpine'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if [ ! -f "webplugin/build/index.html" ]; then
        echo "ERROR: index.html not found in webplugin/build"
        exit 1
      fi
      if [ ! -f "firebase.json" ]; then
        echo "ERROR: firebase.json not found"
        exit 1
      fi
      echo "Build validation successful"

# ------------------------------------------------------------
# Step 5: Firebase deploy (skipped when CDN enabled)
# ------------------------------------------------------------
- name: 'gcr.io/$PROJECT_ID/firebase'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if [ "$_DEPLOY_CDN" = "true" ]; then
        echo "Skipping Firebase deploy (_DEPLOY_CDN=true)"
        exit 0
      fi
      firebase deploy \
        --only hosting:$_FIREBASE_SITE_ID \
        --project $_FIREBASE_PROJECT_ID \
        --token $_FIREBASE_TOKEN

# ------------------------------------------------------------
# Step 6: Sync build output to CDN bucket
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if [ "$_DEPLOY_CDN" = "true" ]; then
        echo "Syncing to CDN bucket"
        gsutil -m rsync -r webplugin/build gs://$_CDN_BUCKET/$_CDN_PREFIX
      else
        echo "Skipping CDN sync"
      fi

# ------------------------------------------------------------
# Step 7: Apply CDN cache headers
# ------------------------------------------------------------
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      if [ "$_DEPLOY_CDN" = "true" ]; then
        _CDN_PREFIX_URI="gs://$_CDN_BUCKET/$_CDN_PREFIX/"

        gsutil_list_file="$(mktemp)"
        gsutil ls -r "$_CDN_PREFIX_URI" > "$gsutil_list_file"

        _CDN_CACHE_OBJECTS="$(
          awk -v prefix="$_CDN_PREFIX_URI" '
            $0 ~ /\/$/ { next }
            index($0, prefix) != 1 { next }
            {
              rel = substr($0, length(prefix) + 1)
            }
            rel ~ /\.js$/ ||
            rel ~ /\.min\.css$/ ||
            rel ~ /\.png$/ ||
            rel ~ /\.webp$/ ||
            rel ~ /\.woff2$/ ||
            rel ~ /\.woff$/ ||
            rel ~ /(^|\/)resources\/.*\.html$/ {
              print $0
            }
          ' "$gsutil_list_file"
        )"

        rm -f "$gsutil_list_file"

        if [ -n "$_CDN_CACHE_OBJECTS" ]; then
          printf '%s\n' "$_CDN_CACHE_OBJECTS" \
            | gsutil -m setmeta -h "Cache-Control:public,max-age=31536000" -I
        fi

        _CDN_SHORT_CACHE_FILES="kommunicate.app v1/kommunicate.app v2/kommunicate.app v3/kommunicate.app kommunicate-widget-3.0.min.js"
        for file_path in $_CDN_SHORT_CACHE_FILES; do
          if gsutil -q ls "gs://$_CDN_BUCKET/$_CDN_PREFIX/$file_path" >/dev/null 2>&1; then
            gsutil setmeta -h "Cache-Control:public,max-age=900" \
              "gs://$_CDN_BUCKET/$_CDN_PREFIX/$file_path"
          fi
        done
      else
        echo "Skipping CDN cache headers"
      fi

