options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_ENV: "test"  # Set this to the target environment (test, release, etc.)
  _BRANCH: "${BRANCH_NAME}"  # Branch name from the trigger
  _FIREBASE_PROJECT_ID: "your-project-id"  # Replacing with dynamic project ID
  _FIREBASE_SITE_ID: "${_BUILD_ENV}_site_id"  # Placeholder for Firebase site ID
  _DEPLOY_CDN: "false"  # Toggle CDN sync
  _CDN_BUCKET: "your-cdn-bucket"  # e.g. kommunicate-widget-cdn
  _CDN_PREFIX: "your-cdn-prefix"  # e.g. widget-test.kommunicate.io

steps:
 # Step 1: Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo clean
        npm cache clean --force
        echo remove
        rm -rf node_modules package-lock.json
        echo Installing source NPM dependencies...
        npm install

 # Step 2: Conditionally run builds based on _BUILD_ENV
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'sh'
    env:
      - '_BRANCH=${_BRANCH}'
      - '_BUILD_ENV=${_BUILD_ENV}'
    args:
      - '-c'
      - |
        echo "Build env:" ${_BUILD_ENV}
        if [ "${_BUILD_ENV}" = "test" ]; then 
          npm run build-test;
        elif [ "${_BUILD_ENV}" = "release" ]; then 
          npm run build-release;
        elif [ "${_BUILD_ENV}" = "staging" ]; then 
          npm run build-staging;
        elif [ "${_BUILD_ENV}" = "prod" ]; then 
          npm run build-prod;
        elif [ "${_BUILD_ENV}" = "prod-enterprise" ]; then 
          npm run build-prod-enterprise;
        elif [ "${_BUILD_ENV}" = "prod-in" ]; then 
          npm run build-prod-in;
        elif [ "${_BUILD_ENV}" = "prod_agenticfirst" ]; then 
          npm run build-prod-agenticfirst;
        elif [ "${_BUILD_ENV}" = "prod-eu" ]; then 
          npm run build-prod-eu;
        elif [ "${_BUILD_ENV}" = "prod_cn" ]; then 
          npm run build-prod-cn;
        elif [ "${_BUILD_ENV}" = "prod_beta" ]; then 
          npm run build-beta;
        else 
          npm run build-test;
        fi

  # Step 3: Updated firebase.json dynamically
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Updating firebase.json with site ID..."
        # Update the site ID dynamically
        sed -i 's/"site": ".*"/"site": "'"${_FIREBASE_SITE_ID}"'"/' firebase.json

  # Step 4: Validating the build directory contains index.html
  - name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Checking if webplugin/build contains index.html..."
        if [ ! -f "webplugin/build/index.html" ]; then
          echo "Error: index.html not found in webplugin/build. Build process might have failed."
          exit 1
        fi
        echo "firebase.json exists, now validating its structure..."
        if [ ! -f "firebase.json" ]; then
          echo "Error: firebase.json file does not exist."
          exit 1
        fi

  # Step 5: Deploy to Firebase Hosting (skipped when CDN deploy is enabled)
  - name: 'gcr.io/$PROJECT_ID/firebase'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_CDN}" = "true" ]; then
          echo "Skipping Firebase deploy because _DEPLOY_CDN=true."
          exit 0
        fi
        firebase deploy --only hosting:${_FIREBASE_SITE_ID} --project ${_FIREBASE_PROJECT_ID} --token ${_FIREBASE_TOKEN}

  # Step 6: Sync build output to CDN bucket (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_CDN}" = "true" ]; then
          gsutil -m rsync -r webplugin/build gs://${_CDN_BUCKET}/${_CDN_PREFIX}
        else
          echo "Skipping CDN sync."
        fi

  # Step 7: Apply CDN cache headers to match Firebase rules (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_CDN}" = "true" ]; then
          if gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.js" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*min.css" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.png" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.webp" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.woff2" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.woff" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/resources/**/*.html" >/dev/null 2>&1; then
            gsutil -m setmeta -h "Cache-Control:public,max-age=31536000" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.js" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*min.css" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.png" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.webp" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.woff2" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/*.woff" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/**/resources/**/*.html"
          fi

          if gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/v2/kommunicate.app" >/dev/null 2>&1 || \
             gsutil -q ls "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/kommunicate-widget-3.0.min.js" >/dev/null 2>&1; then
            gsutil -m setmeta -h "Cache-Control:public,max-age=900" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/v2/kommunicate.app" \
              "gs://${_CDN_BUCKET}/${_CDN_PREFIX}/kommunicate-widget-3.0.min.js"
          fi
        else
          echo "Skipping CDN cache headers."
        fi
