const routes = {
  // '/': 'Home',
  '/dashboard': 'Dashboard',
  '/users': 'Users',
  '/conversations': 'Conversations',
  '/message-groups': 'Message Groups',
  '/components': 'Components',
  '/reports': 'Reports',
  '/bot': 'Bot Integration',
  '/settings/install': 'Install',
  '/settings/team': 'Teammates',
  '/configuration':"Configuration",
  '/autoreply':"Configuration",
  '/settings/profile': "Profile",
  '/settings/quick-replies': 'Quick Replies',
  '/settings/welcome-message': 'Welcome Message',
  '/settings/away-message': 'Away Message',
  '/settings/agent-app': 'Agent App',
  '/settings/conversation-rules':'Conversation Rules',
  '/faq':'FAQ',
  '/settings/billing': 'Billing',
  '/integrations': 'Integrations',
  '/settings/pushnotification': 'Push Notifications',
  '/settings/mailbox': 'Mailbox',
  '/settings/email-notifications': 'Email Notifications',
  '/settings/chat-widget-customization':'Chat Widget',
  '/settings/email-fallback':'Fallback Emails',
  '/settings/webhooks-security':'Webhooks and Security',
};

export default routes;
