exports.AVAIBILITY_STATUS = { "AVAILABLE": 1, "AWAY": 2 }
exports.ROLE_TYPE = { "SUPER_ADMIN": 0, "ADMIN": 1, "AGENT": 2, "BOT": 3, "DEVELOPER": 11 };
exports.EMAIL_NOTIFY = { "UNSUBSCRIBE_ALL": 0, "SUBSCRIBE_ALL": 1, "ONLY_ASSIGNED_CONVERSATION": 4 };
exports. USER_STATUS = {
    AWAY:0,
    ONLINE:1,
    EXPIRED:2,
    DELETED:3
}