exports.AVAIBILITY_STATUS = { "AVAILABLE": 1, "AWAY": 2 }
exports.ROLE_TYPE = { "SUPER_ADMIN": 0, "ADMIN": 1, "AGENT": 2, "BOT": 3 };
exports.EMAIL_NOTIFY = { "UNSUBSCRIBE_ALL": 0, "SUBSCRIBE_ALL": 1, "ONLY_ASSIGNED_TO_ME": 4 };