export const USER_TYPE = {
    AGENT: 1,
    BOT: 2,
    ADMIN: 3
}
export const CONVERSATION_STATS_FILTER_KEY = {
    DAY_WISE_DISTRIBUTION : 1,
    HOUR_WISE_DISTRIBUTION : 2
}

export const MEMORY_CACHING_TIME_DURATION = 2*60*1000   //in Millisec 

export const THIRD_PARTY_INTEGRATION_TYPE = {
    HELPDOCS: 1,
    ZENDESK: 2,
    CLEARBIT: 3,
    AGILE_CRM: 4
}