name: Playwright tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  NODE_ENV: test

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Show test result
        run: |
          echo "Total tests: $(find test -name '*.js' | wc -l)"
          echo "Passed tests: $(grep --no-filename -c 'passed' test/report.xml)"
          echo "Failed tests: $(grep --no-filename -c 'failed' test/report.xml)"
