name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm install
        
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: |
        npx playwright test --workers 16

    - name: Show test result
      run: |
          echo "Total tests: $(find test -name '*.js' | wc -l)"
          echo "Passed tests: $(grep --no-filename -c 'passed' test/report.xml)"
          echo "Failed tests: $(grep --no-filename -c 'failed' test/report.xml)"
