name: Playwright tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy config.js
      run: cp playwright_test/playwright.config.js playwright_test/tests

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test
