name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'A friendly reminder that this issue had no activity for 15 days.'
        stale-pr-message: 'A friendly reminder that this PR had no activity for 15 days.'
        stale-issue-label: 'Stale-issue'
        stale-pr-label: 'Stale-pr'
        days-before-stale: 10
        days-before-close: 15
