Kommunicate =  typeof Kommunicate =='undefined'?{}:Kommunicate;

Kommunicate.defaultLabels = {
    'input.message':'Type your message...',
    'conversations.title': 'Conversations',
    'start.new': 'Start New Conversation',
    'search.contacts': 'Contacts',
    'search.groups': 'Groups',
    'empty.groups': 'No groups yet!',
    'empty.contacts': 'No contacts yet!',
    'empty.messages': 'No messages yet!',
    'no.more.messages': 'No more messages!',
    'empty.conversations': 'No conversations yet!',
    'no.more.conversations': 'No more conversations!',
    'search.placeholder': 'Search...',
    'location.placeholder': 'Enter a location',
    'create.group.title': 'Create Group',
    'members.title': 'Members',
    'add.members.title': 'Add Member',
    'remove.member': 'Remove Member',
    'change.role': 'Change Role',
    'group.info.update': 'Update',
    'group.info.updating': 'Updating...',
    'add.group.icon': 'Add Group Icon',
    'group.deleted': 'Group has been deleted',
    'change.group.icon': 'Change Group Icon',
    'group.title': 'Group Title',
    'group.type': 'Group Type',
    'group.create.submit': 'Creating Group...',
    'blocked': 'You have blocked this user',
    'group.chat.disabled': 'You are no longer part of this group!',
    'block.user.alert': 'Are you sure you want to block this user?',
    'unblock.user.alert': 'Are you sure you want to unblock this user?',
    'exit.group.alert': 'Are you sure you want to exit this group?',
    'remove.member.alert': 'Are you sure you want to remove this member?',
    'clear.messages.alert': 'Are you sure you want to delete all the conversation?',
    'typing': 'typing...',
    'is.typing': 'is typing...',
    'online': 'Online',
    'offline': 'Offline',
    'clear.messages': 'Clear Messages',
    'delete': 'Delete',
    'reply': 'Reply',
    'forward': 'Forward',
    'copy': 'Copy',
    'block.user': 'Block User',
    'unblock.user': 'Unblock User',
    'group.info.title': 'Group Info',
    'exit.group': 'Exit Group',
    'location.share.title': 'Location Sharing',
    'my.location': 'My Location',
    'send': 'Send',
    'send.message': 'Send Message',
    'smiley': 'Smiley',
    'close': 'Close',
    'edit': 'Edit',
    'save': 'Save',
    'file.attachment': 'Files & Photos',
    'file.attach.title': 'Attach File',
    'last.seen': 'Last seen',
    'last.seen.on': 'Last seen on',
    'hour':' hour',
    'min':' min',
    'yesterday':'yesterday',
    'hours':' hours',
    'mins':' mins',
    'time.format.AM':'AM',
    'time.format.PM':'PM',
    'time.format.am':'am',
    'time.format.pm':'pm',
    'user.delete':'This user has been deleted',
    'ago': 'ago',
    'admin':'Admin',
    'user':'User',
    'moderator':'Moderator',
    'member':'Member',
    'public':'Public',
    'private':'Private',
    'open':'Open',
    'you':'You',
    'away':'Away',
    'closed.conversation.message':'This conversation has been marked as resolved. If you have other queries, just send a message here or start a new conversation.',
    'search.faq':'Search in FAQs...',
    'looking.for.something.else':'Looking for something else?',
    'talk.to.agent': 'Talk to an agent',
    'how.to.reachout': 'How may we reach you?',
    'email.error.alert': 'It seems you have entered an invalid email',
    'group.metadata': {
        'CREATE_GROUP_MESSAGE': ':adminName created group :groupName',
        'REMOVE_MEMBER_MESSAGE': ':adminName removed :userName',
        'ADD_MEMBER_MESSAGE': ':adminName added :userName',
        'JOIN_MEMBER_MESSAGE': ':userName joined',
        'GROUP_NAME_CHANGE_MESSAGE': 'Group name changed to :groupName',
        'GROUP_ICON_CHANGE_MESSAGE': 'Group icon changed',
        'GROUP_LEFT_MESSAGE': ':userName left',
        'DELETED_GROUP_MESSAGE': ':adminName deleted group',
        'GROUP_USER_ROLE_UPDATED_MESSAGE': ':userName is :role now',
        'GROUP_META_DATA_UPDATED_MESSAGE': '',
        'ALERT': '',
        'HIDE': ''
    },
    'lead.collection': {
                'email':'Email',
                'name':'Name',
                'phone':'Contact Number',
                'heading':'Before starting, we just need a few details so that we may serve you better',
                'submit':'Start Conversation',
    }
}
