//exports.EVENTS = {"KM-001":"1", "KM-002":"2", "KM-003":"3", "KM-004":"4"};
exports.EVENTS = {"CONVERSATION_STARTED":"1"}
exports.IN_APP_MESSAGE_CETAGORY={WELCOME_MESSAGE:1};
exports.EVENT_STATUS ={ENABLED:"1",DISABLED:"2",DELETED:"3"};
