//exports.EVENTS = {"KM-001":"1", "KM-002":"2", "KM-003":"3", "KM-004":"4"};
exports.EVENTS = { "CONVERSATION_STARTED": "1" }
exports.IN_APP_MESSAGE_CETAGORY = { WELCOME_MESSAGE: 1 };
exports.EVENT_STATUS = { ENABLED: "1", DISABLED: "2", DELETED: "3" };
exports.EVENT_ID = { WELCOME_MESSAGE: "3", AWAY_MESSAGE: { KNOWN: "1", ANONYMOUS: "2" } }
exports.CATEGORY = { WELCOME_MESSAGE: "1", AWAY_MESSAGE: "2" }
